# This file was generated by GoReleaser. DO NOT EDIT.
cask "beaver" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "22f29bb8bc0768931471a888fa10d46ee7862f2489e1bc6d35aab716e1823f14"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "145e5e187986be0ac5f76ee0b1944c4cc7ff9de532108bc0eb66076dc064305d"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "98ebc7dabc33d3a47a82b22fef76513659668e9dd48b66605518a11cf779afaa"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fe18b39408083e50a2a2044212b6f0145ffa91bd341cbe2ec225484f7cda3d3"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "beaver"
  desc "A fast terminal file manager built with Go and Bubble Tea"
  homepage "https://github.com/Beaver-family/beaver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beaver"

  # No zap stanza required

end
