# This file was generated by GoReleaser. DO NOT EDIT.
cask "beaver" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "54b1e2f5cee0cf829a910f5c7fe43de2db0edc062b8bfa1cba0cef70d9385b96"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f3a0e60411dff78c754c93e566a0ef59b0b6c70693e60e8ac8ae32ddbf66c5b"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd89083401e6b615b7b0391742a874e379122470a9c6f86de63dd1c6de53ee6e"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "244fda676345fc27bb048fe9fd96965047dad4f12b9b6e136f26f87b19fc5295"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "beaver"
  desc "A fast terminal file manager built with Go and Bubble Tea"
  homepage "https://github.com/Beaver-family/beaver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beaver"

  # No zap stanza required

end
