# This file was generated by GoReleaser. DO NOT EDIT.
cask "beaver" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "c57ef2fe9b0f1f71d0914edda7ebacc3c147ab19c351e91c3571f01f61e16ed7"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc87aea970e0e2ba8197dbceec81dafd094d7d7d5f0b77250341cf2de44933ab"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dff7c5e0cc435b2aff4b14683f0c3bc8b1f6b7382e40e6dd3a94d101bb9fe1df"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aaba3473faa12c3a59567abf017ef261c349938e3203703d15b39ea3fbc05085"
      url "https://github.com/Beaver-family/beaver/releases/download/v#{version}/beaver_#{version}_linux_arm64.tar.gz"
    end
  end

  name "beaver"
  desc "A fast terminal file manager built with Go and Bubble Tea"
  homepage "https://github.com/Beaver-family/beaver"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "beaver"

  # No zap stanza required

  caveats <<~EOS
    macOS Gatekeeper may block beaver on first run.
    If you see "cannot be verified", run once:
      xattr -d com.apple.quarantine $(which beaver)
  EOS
end
